version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: tomato-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tomato_db
      MYSQL_USER: tomato_user
      MYSQL_PASSWORD: tomato_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: